### ISSUE TITLE
npm ERR! code 1

### ISSUE THREAD

**Issue by jeylites** [philhartung/aes67-sender-gui#1]
@philhartung 

Trying to get this going, getting the following error. 

Machine: Apple M1 (Ventura)
NPM: 9.5.0
Node: v18.15.0

`pm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated electron-notarize@1.2.2: Please use @electron/notarize moving forward.  There is no API change, just a package name change
npm ERR! code 1
npm ERR! path /Users/jk/aes67-sender-gui/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
npm ERR!     at EventEmitter.<anonymous> (/Users/jk/aes67-sender-gui/node_modules/got/source/as-stream.js:35:24)
npm ERR!     at EventEmitter.emit (node:events:513:28)
npm ERR!     at module.exports (/Users/jk/aes67-sender-gui/node_modules/got/source/get-response.js:22:10)
npm ERR!     at ClientRequest.handleResponse (/Users/jeykasi/aes67-sender-gui/node_modules/got/source/request-as-event-emitter.js:155:5)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:525:35)
npm ERR!     at origin.emit (/Users/jk/aes67-sender-gui/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:542:22)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jk/.npm/_logs/2023-03-30T16_58_44_081Z-debug-0.log
jk@Macmini aes67-sender-gui % 
`

**Comment by philhartung** [comment]
This project will no longer be maintained. Please use https://github.com/philhartung/aes67-sender or something else
